import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { SchemaMap, TableCatalog } from '#/lib/types'

/**
 * Internal schema metadata lives in `local/` — gitignored by this repo, which is
 * public, and kept in its own private git repo. Both files are hand/extractor
 * produced and may simply be absent: every reader here returns null instead of
 * throwing, and the lens shows the gap in its staleness panel.
 *
 * `schema-map.json` is regenerated by:
 *   python3 ~/Work/buildots/pycode/local_dev/schema_map/extract.py
 */

const LOCAL_DIR = 'local'

async function readLocalJson<T>(fileName: string): Promise<T | null> {
  try {
    const path = resolve(process.cwd(), LOCAL_DIR, fileName)
    return JSON.parse(await readFile(path, 'utf-8')) as T
  } catch {
    return null
  }
}

export function readTableCatalog(): Promise<TableCatalog | null> {
  return readLocalJson<TableCatalog>('table-catalog.json')
}

export function readSchemaMap(): Promise<SchemaMap | null> {
  return readLocalJson<SchemaMap>('schema-map.json')
}
