import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { SchemaMap, TableCatalog } from '#/lib/types'

/**
 * Internal schema metadata lives in `local/` — gitignored by this repo, which is
 * public, and kept in its own private git repo. Every file is hand- or
 * extractor-produced and may simply be absent: each reader returns null instead
 * of throwing, and the lens shows the gap in its staleness panel.
 *
 * Metadata is per schema. `public`'s grouping says nothing about `aggs_staged`
 * and neither says anything about `pg_catalog`, so a single shared file would
 * describe one schema and quietly mislabel the rest:
 *
 *   local/<schema>/table-catalog.json   groups, hand-curated
 *   local/<schema>/schema-map.json      extractor output (edges, conventions)
 *
 * The flat `local/table-catalog.json` and `local/schema-map.json` are still read
 * for `public`, since that is where they came from and moving someone's private
 * files out from under them is not this code's business.
 *
 * `schema-map.json` is regenerated by:
 *   python3 ~/Work/buildots/pycode/local_dev/schema_map/extract.py
 */

const LOCAL_DIR = 'local'
const LEGACY_SCHEMA = 'public'

async function readLocalJson<T>(...segments: string[]): Promise<T | null> {
  try {
    const path = resolve(process.cwd(), LOCAL_DIR, ...segments)
    return JSON.parse(await readFile(path, 'utf-8')) as T
  } catch {
    return null
  }
}

/** Per-schema file first; the flat legacy file only ever answers for `public`. */
async function readForSchema<T>(schema: string, fileName: string): Promise<T | null> {
  const scoped = await readLocalJson<T>(schema, fileName)
  if (scoped) return scoped
  if (schema === LEGACY_SCHEMA) return readLocalJson<T>(fileName)
  return null
}

export function readTableCatalog(schema: string): Promise<TableCatalog | null> {
  return readForSchema<TableCatalog>(schema, 'table-catalog.json')
}

export function readSchemaMap(schema: string): Promise<SchemaMap | null> {
  return readForSchema<SchemaMap>(schema, 'schema-map.json')
}
