import { describe, expect, it } from 'vitest'
import { buildDdlSql, ddlColumnLine, quoteIdent, quoteLiteral } from '#/lib/inspect/ddl'
import type { DdlColumn } from '#/lib/types'

function column(overrides: Partial<DdlColumn> = {}): DdlColumn {
  return {
    name: 'id',
    type: 'integer',
    notNull: true,
    default: null,
    identity: null,
    generated: null,
    comment: null,
    ...overrides,
  }
}

describe('quoteIdent', () => {
  it('leaves a plain lowercase identifier bare', () => {
    expect(quoteIdent('user_id')).toBe('user_id')
  })

  it('quotes mixed case, spaces, and reserved words', () => {
    expect(quoteIdent('userId')).toBe('"userId"')
    expect(quoteIdent('my col')).toBe('"my col"')
    expect(quoteIdent('order')).toBe('"order"')
  })

  it('doubles an embedded quote', () => {
    expect(quoteIdent('we"ird')).toBe('"we""ird"')
  })
})

describe('quoteLiteral', () => {
  it('doubles single quotes', () => {
    expect(quoteLiteral("it's")).toBe("'it''s'")
  })
})

describe('ddlColumnLine', () => {
  it('puts NOT NULL after the default, as pg_dump does', () => {
    expect(ddlColumnLine(column({ name: 'n', type: 'integer', default: '5' }))).toBe(
      'n integer DEFAULT 5 NOT NULL',
    )
  })

  it('emits an identity clause instead of a default', () => {
    expect(
      ddlColumnLine(column({ identity: 'BY DEFAULT', default: 'nextval(\'s\')' })),
    ).toBe('id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL')
  })

  it('emits a generated column as stored', () => {
    expect(
      ddlColumnLine(column({ name: 'total', type: 'numeric', notNull: false, generated: 'a + b' })),
    ).toBe('total numeric GENERATED ALWAYS AS (a + b) STORED')
  })

  it('omits NOT NULL for a nullable column', () => {
    expect(ddlColumnLine(column({ name: 'note', type: 'text', notNull: false }))).toBe(
      'note text',
    )
  })
})

describe('buildDdlSql', () => {
  const parts = {
    schema: 'public',
    table: 'orders',
    columns: [
      column({ name: 'id', identity: 'BY DEFAULT' }),
      column({ name: 'user_id', type: 'integer', comment: 'who ordered' }),
      column({ name: 'note', type: 'text', notNull: false }),
    ],
    constraints: [
      { name: 'orders_user_fk', kind: 'f' as const, definition: 'FOREIGN KEY (user_id) REFERENCES users(id)' },
      { name: 'orders_pkey', kind: 'p' as const, definition: 'PRIMARY KEY (id)' },
    ],
    indexes: [
      { name: 'orders_pkey', definition: 'CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id)', constraintBacked: true, isPrimary: true, isUnique: true },
      { name: 'orders_user_idx', definition: 'CREATE INDEX orders_user_idx ON public.orders USING btree (user_id)', constraintBacked: false, isPrimary: false, isUnique: false },
    ],
    tableComment: "customers' orders",
  }

  it('writes a replayable CREATE TABLE with constraints inside it', () => {
    const sql = buildDdlSql(parts)
    expect(sql).toContain('CREATE TABLE public.orders (')
    expect(sql).toContain('    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,')
    expect(sql).toContain('    CONSTRAINT orders_pkey PRIMARY KEY (id),')
    expect(sql).toContain('    CONSTRAINT orders_user_fk FOREIGN KEY (user_id) REFERENCES users(id)')
  })

  it('orders the primary key before the foreign key', () => {
    const sql = buildDdlSql(parts)
    expect(sql.indexOf('orders_pkey PRIMARY KEY')).toBeLessThan(sql.indexOf('orders_user_fk'))
  })

  it('drops the index a constraint already creates, keeping the standalone one', () => {
    const sql = buildDdlSql(parts)
    expect(sql).toContain('CREATE INDEX orders_user_idx')
    expect(sql).not.toContain('CREATE UNIQUE INDEX orders_pkey')
  })

  it('emits comments last, with quotes escaped', () => {
    const sql = buildDdlSql(parts)
    expect(sql).toContain("COMMENT ON TABLE public.orders IS 'customers'' orders';")
    expect(sql).toContain("COMMENT ON COLUMN public.orders.user_id IS 'who ordered';")
    expect(sql.indexOf('COMMENT ON TABLE')).toBeGreaterThan(sql.indexOf('CREATE INDEX'))
  })

  it('handles a table with no columns at all', () => {
    expect(
      buildDdlSql({ ...parts, columns: [], constraints: [], indexes: [], tableComment: null }),
    ).toBe('CREATE TABLE public.orders ();\n')
  })
})
