/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSchemaTableIndexRouteImport } from './routes/t/$schema/$table/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSchemaTableIndexRoute = TSchemaTableIndexRouteImport.update({
  id: '/t/$schema/$table/',
  path: '/t/$schema/$table/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t/$schema/$table/': typeof TSchemaTableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t/$schema/$table': typeof TSchemaTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t/$schema/$table/': typeof TSchemaTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/t/$schema/$table/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/t/$schema/$table'
  id: '__root__' | '/' | '/t/$schema/$table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TSchemaTableIndexRoute: typeof TSchemaTableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$schema/$table/': {
      id: '/t/$schema/$table/'
      path: '/t/$schema/$table'
      fullPath: '/t/$schema/$table/'
      preLoaderRoute: typeof TSchemaTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TSchemaTableIndexRoute: TSchemaTableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
