/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PressureSchemaRouteImport } from './routes/pressure/$schema'
import { Route as LensSchemaIndexRouteImport } from './routes/lens/$schema/index'
import { Route as LensSchemaOrphansRouteImport } from './routes/lens/$schema/orphans'
import { Route as TSchemaTableIndexRouteImport } from './routes/t/$schema/$table/index'
import { Route as LensSchemaTTableRouteImport } from './routes/lens/$schema/t/$table'
import { Route as LensSchemaGGroupRouteImport } from './routes/lens/$schema/g/$group'
import { Route as TSchemaTableRowIdRouteImport } from './routes/t/$schema/$table/row/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressureSchemaRoute = PressureSchemaRouteImport.update({
  id: '/pressure/$schema',
  path: '/pressure/$schema',
  getParentRoute: () => rootRouteImport,
} as any)
const LensSchemaIndexRoute = LensSchemaIndexRouteImport.update({
  id: '/lens/$schema/',
  path: '/lens/$schema/',
  getParentRoute: () => rootRouteImport,
} as any)
const LensSchemaOrphansRoute = LensSchemaOrphansRouteImport.update({
  id: '/lens/$schema/orphans',
  path: '/lens/$schema/orphans',
  getParentRoute: () => rootRouteImport,
} as any)
const TSchemaTableIndexRoute = TSchemaTableIndexRouteImport.update({
  id: '/t/$schema/$table/',
  path: '/t/$schema/$table/',
  getParentRoute: () => rootRouteImport,
} as any)
const LensSchemaTTableRoute = LensSchemaTTableRouteImport.update({
  id: '/lens/$schema/t/$table',
  path: '/lens/$schema/t/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const LensSchemaGGroupRoute = LensSchemaGGroupRouteImport.update({
  id: '/lens/$schema/g/$group',
  path: '/lens/$schema/g/$group',
  getParentRoute: () => rootRouteImport,
} as any)
const TSchemaTableRowIdRoute = TSchemaTableRowIdRouteImport.update({
  id: '/t/$schema/$table/row/$id',
  path: '/t/$schema/$table/row/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/settings': typeof SettingsRoute
  '/pressure/$schema': typeof PressureSchemaRoute
  '/lens/$schema/orphans': typeof LensSchemaOrphansRoute
  '/lens/$schema/': typeof LensSchemaIndexRoute
  '/lens/$schema/g/$group': typeof LensSchemaGGroupRoute
  '/lens/$schema/t/$table': typeof LensSchemaTTableRoute
  '/t/$schema/$table/': typeof TSchemaTableIndexRoute
  '/t/$schema/$table/row/$id': typeof TSchemaTableRowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/settings': typeof SettingsRoute
  '/pressure/$schema': typeof PressureSchemaRoute
  '/lens/$schema/orphans': typeof LensSchemaOrphansRoute
  '/lens/$schema': typeof LensSchemaIndexRoute
  '/lens/$schema/g/$group': typeof LensSchemaGGroupRoute
  '/lens/$schema/t/$table': typeof LensSchemaTTableRoute
  '/t/$schema/$table': typeof TSchemaTableIndexRoute
  '/t/$schema/$table/row/$id': typeof TSchemaTableRowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/settings': typeof SettingsRoute
  '/pressure/$schema': typeof PressureSchemaRoute
  '/lens/$schema/orphans': typeof LensSchemaOrphansRoute
  '/lens/$schema/': typeof LensSchemaIndexRoute
  '/lens/$schema/g/$group': typeof LensSchemaGGroupRoute
  '/lens/$schema/t/$table': typeof LensSchemaTTableRoute
  '/t/$schema/$table/': typeof TSchemaTableIndexRoute
  '/t/$schema/$table/row/$id': typeof TSchemaTableRowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/settings'
    | '/pressure/$schema'
    | '/lens/$schema/orphans'
    | '/lens/$schema/'
    | '/lens/$schema/g/$group'
    | '/lens/$schema/t/$table'
    | '/t/$schema/$table/'
    | '/t/$schema/$table/row/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/settings'
    | '/pressure/$schema'
    | '/lens/$schema/orphans'
    | '/lens/$schema'
    | '/lens/$schema/g/$group'
    | '/lens/$schema/t/$table'
    | '/t/$schema/$table'
    | '/t/$schema/$table/row/$id'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/settings'
    | '/pressure/$schema'
    | '/lens/$schema/orphans'
    | '/lens/$schema/'
    | '/lens/$schema/g/$group'
    | '/lens/$schema/t/$table'
    | '/t/$schema/$table/'
    | '/t/$schema/$table/row/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  SettingsRoute: typeof SettingsRoute
  PressureSchemaRoute: typeof PressureSchemaRoute
  LensSchemaOrphansRoute: typeof LensSchemaOrphansRoute
  LensSchemaIndexRoute: typeof LensSchemaIndexRoute
  LensSchemaGGroupRoute: typeof LensSchemaGGroupRoute
  LensSchemaTTableRoute: typeof LensSchemaTTableRoute
  TSchemaTableIndexRoute: typeof TSchemaTableIndexRoute
  TSchemaTableRowIdRoute: typeof TSchemaTableRowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressure/$schema': {
      id: '/pressure/$schema'
      path: '/pressure/$schema'
      fullPath: '/pressure/$schema'
      preLoaderRoute: typeof PressureSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens/$schema/': {
      id: '/lens/$schema/'
      path: '/lens/$schema'
      fullPath: '/lens/$schema/'
      preLoaderRoute: typeof LensSchemaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens/$schema/orphans': {
      id: '/lens/$schema/orphans'
      path: '/lens/$schema/orphans'
      fullPath: '/lens/$schema/orphans'
      preLoaderRoute: typeof LensSchemaOrphansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$schema/$table/': {
      id: '/t/$schema/$table/'
      path: '/t/$schema/$table'
      fullPath: '/t/$schema/$table/'
      preLoaderRoute: typeof TSchemaTableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens/$schema/t/$table': {
      id: '/lens/$schema/t/$table'
      path: '/lens/$schema/t/$table'
      fullPath: '/lens/$schema/t/$table'
      preLoaderRoute: typeof LensSchemaTTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens/$schema/g/$group': {
      id: '/lens/$schema/g/$group'
      path: '/lens/$schema/g/$group'
      fullPath: '/lens/$schema/g/$group'
      preLoaderRoute: typeof LensSchemaGGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$schema/$table/row/$id': {
      id: '/t/$schema/$table/row/$id'
      path: '/t/$schema/$table/row/$id'
      fullPath: '/t/$schema/$table/row/$id'
      preLoaderRoute: typeof TSchemaTableRowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  SettingsRoute: SettingsRoute,
  PressureSchemaRoute: PressureSchemaRoute,
  LensSchemaOrphansRoute: LensSchemaOrphansRoute,
  LensSchemaIndexRoute: LensSchemaIndexRoute,
  LensSchemaGGroupRoute: LensSchemaGGroupRoute,
  LensSchemaTTableRoute: LensSchemaTTableRoute,
  TSchemaTableIndexRoute: TSchemaTableIndexRoute,
  TSchemaTableRowIdRoute: TSchemaTableRowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
