/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerPreviewRouteImport } from './routes/explorer/preview'
import { Route as ExplorerDocumentsRouteImport } from './routes/explorer/documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerPreviewRoute = ExplorerPreviewRouteImport.update({
  id: '/explorer/preview',
  path: '/explorer/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerDocumentsRoute = ExplorerDocumentsRouteImport.update({
  id: '/explorer/documents',
  path: '/explorer/documents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer/documents': typeof ExplorerDocumentsRoute
  '/explorer/preview': typeof ExplorerPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer/documents': typeof ExplorerDocumentsRoute
  '/explorer/preview': typeof ExplorerPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer/documents': typeof ExplorerDocumentsRoute
  '/explorer/preview': typeof ExplorerPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explorer/documents' | '/explorer/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explorer/documents' | '/explorer/preview'
  id: '__root__' | '/' | '/explorer/documents' | '/explorer/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerDocumentsRoute: typeof ExplorerDocumentsRoute
  ExplorerPreviewRoute: typeof ExplorerPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/preview': {
      id: '/explorer/preview'
      path: '/explorer/preview'
      fullPath: '/explorer/preview'
      preLoaderRoute: typeof ExplorerPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/documents': {
      id: '/explorer/documents'
      path: '/explorer/documents'
      fullPath: '/explorer/documents'
      preLoaderRoute: typeof ExplorerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerDocumentsRoute: ExplorerDocumentsRoute,
  ExplorerPreviewRoute: ExplorerPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
